In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3])
a

array([1, 2, 3])

1d array

In [ ]:
a = np.array([1,2,3,4,5,6])
print(a.ndim)
a

1


array([1, 2, 3, 4, 5, 6])

2d array

In [19]:
ar2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(ar2.ndim)
ar2

2


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

3d array

In [20]:
ar3 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
print(ar3.ndim)
ar3

2


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

10d array

In [22]:
arn = np.array([1,2,3,4,5,6],ndmin=10)
print(arn.ndim)
arn

10


array([[[[[[[[[[1, 2, 3, 4, 5, 6]]]]]]]]]])